name: Schedule
form: $/patrickjamal/eventsschedule/models/schedule/fields.yaml
modelClass: PatrickJamal\EventsSchedule\Models\Schedule
defaultRedirect: patrickjamal/eventsschedule/schedule
create:
    redirect: 'patrickjamal/eventsschedule/schedule/update/:id'
    redirectClose: patrickjamal/eventsschedule/schedule
update:
    redirect: patrickjamal/eventsschedule/schedule
    redirectClose: patrickjamal/eventsschedule/schedule
